export interface GetAllProduct{
    productNumber : string;
    productName  : string;
    description : string;
    productSpecficTraining : string;
    price : string;
    wearable : string;
    softwareUpdateSupport : string;
    portability : string;
    compact : string;
    batterySupport : string;
    thirdPartyDeviceSupport : string;
    safeToFlyCertification : string;
    touchScreenSupport : string;
    screenSize : string;
    multiPatientSupport : string;
    cyberSecurity : string;
    image : HTMLImageElement
}