name: Resharper Code Analysis
 
on: 
    push:
        branches: [main]
 
jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 3.1.101
          
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
        
      - name: Add package
        run: dotnet add AssistAPurchaseWebApiTest/AssistAPurchaseWebApiTest.csproj package xunit --version 2.4.1
        
      - name: Add package
        run: dotnet add AssistAPurchase.Integration.Tests/AssistAPurchase.Integration.Tests.csproj package xunit --version 2.4.1
       
      - name: Run resharper duplicate code check
        run: jb dupfinder AssistAPurchase.sln /output=dupreport.xml
        
      - name: Run resharper InspectCode code check
        run: jb inspectcode AssistAPurchase.sln /output=insreport.xml
       
      - name: Check Reports
        run: powershell ./resharper.ps1


